version: '3.6'
services:
  nightfall_code_scanner_build:
    image: builder
    build:
      context: .
      target: builder
    environment:
      GO_ENV: ci
    command: ./nightfall_dlp

  nightfall_code_scanner:
    build:
      context: .
    image: nightfallai/nightfall_code_scanner

  wait:
    image: deliveroo/circleci:0.2.8
