version: 2.1

orbs:
  nightfall_code_scanner: nightfall/nightfall_code_scanner@2.2.0

jobs:
  build:
    docker:
      - image: deliveroo/circleci:0.2.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build docker
          command: ci build
      - run:
          name: test docker
          command: ci run --rm nightfall_dlp_build make test
      - run:
          name: Clean up reusable Docker
          command: clean_up_reusable_docker

  lint:
    docker:
      - image: deliveroo/circleci:0.2.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build docker
          command: ci build
      - run:
          name: lint code
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
               CHECK_LEVEL="github-check"
            else
               CHECK_LEVEL="github-pr-check"
            fi
            ci run --no-deps \
            -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
            -e CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME \
            -e CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME \
            -e CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER \
            -e CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST \
            -e CIRCLE_SHA1=$CIRCLE_SHA1 \
            -e REVIEWDOG_TOKEN=$REVIEWDOG_TOKEN \
            --rm nightfall_dlp_build \
            sh -c '$(go env GOPATH)/bin/golangci-lint run \
              | $(go env GOPATH)/bin/reviewdog -f=golangci-lint -name=golangci -reporter='"$CHECK_LEVEL"' -level=error'
      - run:
          name: Clean up reusable Docker
          command: clean_up_reusable_docker

  push-to-dockerhub:
    docker:
      - image: deliveroo/circleci:0.2.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build
          command: ci build
      - run:
          name: Tag docker container
          command: make dockertag
      - run:
          name: Push image to docker hub
          command: |
            push_image_to_docker_hub \
            nightfallai/$CONTAINER_NAME:$CIRCLE_SHA1 \
            nightfallai/$CONTAINER_NAME:latest
          environment:
            CONTAINER_NAME: nightfall_dlp

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: build
      - lint:
          context: build
      - nightfall_code_scanner/scan:
          event_before: << pipeline.git.base_revision >>
      - push-to-dockerhub:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master
