// Code generated by MockGen. DO NOT EDIT.
// Source: ../../clients/diffreviewer/diff_reviewer.go

// Package diffreviewer_mock is a generated GoMock package.
package diffreviewer_mock

import (
	gomock "github.com/golang/mock/gomock"
	diffreviewer "github.com/watchtowerai/nightfall_dlp/internal/clients/diffreviewer"
	reflect "reflect"
)

// DiffReviewer is a mock of DiffReviewer interface
type DiffReviewer struct {
	ctrl     *gomock.Controller
	recorder *DiffReviewerMockRecorder
}

// DiffReviewerMockRecorder is the mock recorder for DiffReviewer
type DiffReviewerMockRecorder struct {
	mock *DiffReviewer
}

// NewDiffReviewer creates a new mock instance
func NewDiffReviewer(ctrl *gomock.Controller) *DiffReviewer {
	mock := &DiffReviewer{ctrl: ctrl}
	mock.recorder = &DiffReviewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *DiffReviewer) EXPECT() *DiffReviewerMockRecorder {
	return m.recorder
}

// LoadConfig mocks base method
func (m *DiffReviewer) LoadConfig() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfig")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadConfig indicates an expected call of LoadConfig
func (mr *DiffReviewerMockRecorder) LoadConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfig", reflect.TypeOf((*DiffReviewer)(nil).LoadConfig))
}

// GetDiff mocks base method
func (m *DiffReviewer) GetDiff() ([]*diffreviewer.FileDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiff")
	ret0, _ := ret[0].([]*diffreviewer.FileDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiff indicates an expected call of GetDiff
func (mr *DiffReviewerMockRecorder) GetDiff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiff", reflect.TypeOf((*DiffReviewer)(nil).GetDiff))
}

// WriteComments mocks base method
func (m *DiffReviewer) WriteComments(comments []*diffreviewer.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteComments", comments)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteComments indicates an expected call of WriteComments
func (mr *DiffReviewerMockRecorder) WriteComments(comments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteComments", reflect.TypeOf((*DiffReviewer)(nil).WriteComments), comments)
}
