// Code generated by MockGen. DO NOT EDIT.
// Source: ../nightfallintf/nightfall_api.go

// Package nightfallapi_mock is a generated GoMock package.
package nightfallapi_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nightfallintf "github.com/nightfallai/nightfall_cli/internal/interfaces/nightfallintf"
)

// NightfallAPI is a mock of NightfallAPI interface
type NightfallAPI struct {
	ctrl     *gomock.Controller
	recorder *NightfallAPIMockRecorder
}

// NightfallAPIMockRecorder is the mock recorder for NightfallAPI
type NightfallAPIMockRecorder struct {
	mock *NightfallAPI
}

// NewNightfallAPI creates a new mock instance
func NewNightfallAPI(ctrl *gomock.Controller) *NightfallAPI {
	mock := &NightfallAPI{ctrl: ctrl}
	mock.recorder = &NightfallAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *NightfallAPI) EXPECT() *NightfallAPIMockRecorder {
	return m.recorder
}

// ScanAPI mocks base method
func (m *NightfallAPI) ScanAPI() nightfallintf.NightfallScanAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanAPI")
	ret0, _ := ret[0].(nightfallintf.NightfallScanAPI)
	return ret0
}

// ScanAPI indicates an expected call of ScanAPI
func (mr *NightfallAPIMockRecorder) ScanAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAPI", reflect.TypeOf((*NightfallAPI)(nil).ScanAPI))
}
